version: "3.8"

services:
  backend:
    build:
      context: .
      target: dev
    image: kvdomingo/lsfm-api:latest
    env_file: .env
    volumes:
      - .:/backend

  frontend:
    build: ./web/app
    image: kvdomingo/lsfm-app:latest
    env_file: ./web/app/.env
    volumes:
      - ./web/app:/web

  proxy:
    image: nginx:latest
    ports:
      - 8000:8000
    command:
      - nginx
      - "-g"
      - daemon off;
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
