/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const DigitalsouvenirMemberLazyRouteImport = createFileRoute(
  '/digitalsouvenir/$member',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DigitalsouvenirMemberLazyRoute =
  DigitalsouvenirMemberLazyRouteImport.update({
    id: '/digitalsouvenir/$member',
    path: '/digitalsouvenir/$member',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/digitalsouvenir/$member.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/digitalsouvenir/$member': typeof DigitalsouvenirMemberLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/digitalsouvenir/$member': typeof DigitalsouvenirMemberLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/digitalsouvenir/$member': typeof DigitalsouvenirMemberLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digitalsouvenir/$member'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digitalsouvenir/$member'
  id: '__root__' | '/' | '/digitalsouvenir/$member'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DigitalsouvenirMemberLazyRoute: typeof DigitalsouvenirMemberLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalsouvenir/$member': {
      id: '/digitalsouvenir/$member'
      path: '/digitalsouvenir/$member'
      fullPath: '/digitalsouvenir/$member'
      preLoaderRoute: typeof DigitalsouvenirMemberLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DigitalsouvenirMemberLazyRoute: DigitalsouvenirMemberLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
