/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const DigitalsouvenirMemberLazyImport = createFileRoute(
  '/digitalsouvenir/$member',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DigitalsouvenirMemberLazyRoute = DigitalsouvenirMemberLazyImport.update({
  path: '/digitalsouvenir/$member',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/digitalsouvenir/$member.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/digitalsouvenir/$member': {
      id: '/digitalsouvenir/$member'
      path: '/digitalsouvenir/$member'
      fullPath: '/digitalsouvenir/$member'
      preLoaderRoute: typeof DigitalsouvenirMemberLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DigitalsouvenirMemberLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/digitalsouvenir/$member"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/digitalsouvenir/$member": {
      "filePath": "digitalsouvenir/$member.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
